{% set name = "mne-bids-pipeline" %}
{% set version = "1.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b457c78bf44748143b32dad15e3885d29d654b40b5c9f64937ca3fe80e8638d2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - mne_bids_pipeline = mne_bids_pipeline._main:main

requirements:
  host:
    - pip
    - hatchling
    - hatch-vcs
    - python >=3.10
  run:
    - python >=3.10
    - psutil
    - packaging
    - joblib >=0.14
    - threadpoolctl
    - dask
    - bokeh
    - jupyter-server-proxy
    - scikit-learn
    - numpy
    - scipy
    - matplotlib-base
    - pandas
    - pyarrow
    - seaborn
    - json_tricks
    - rich
    - python-picard
    - qtpy
    - pyvista
    - pyvistaqt
    - openpyxl
    - autoreject
    - mne-base >=1.7
    - h5io
    - mne-bids
    - nibabel
    - filelock
    - pydantic >=2.0.0
    - annotated-types
    - tqdm

test:
  imports:
    - mne_bids_pipeline
  commands:
    - pip check
    - mne_bids_pipeline --version
  requires:
    - pip

about:
  home: https://pypi.org/project/mne-bids-pipeline/
  summary: A standardized processing pipeline for your MEG and EEG data
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - larsoner
    - hoechenberger
