{% set name = "mne-bids-pipeline" %}
{% set version = "1.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 665c6b10c15a07851f1f011ffac428715e23a3b16540c1ac8dc1ce6af9308b70

build:
  entry_points:
    - mne_bids_pipeline = mne_bids_pipeline._main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - annotated-types
    - autoreject
    - bokeh
    - dask
    - filelock
    - h5io
    - joblib >=0.14
    - json_tricks
    - jupyter-server-proxy
    - matplotlib-base
    - meegkit
    - mne-bids
    - mne-icalabel
    - mne-base >=1.7
    - nibabel
    - numpy
    - openpyxl
    - packaging
    - pandas
    - psutil
    - pyarrow
    - pydantic >=2.0.0
    - python-picard
    - pyvista
    - pyvistaqt
    - qtpy
    - rich
    - scikit-learn
    - scipy
    - seaborn
    - threadpoolctl

test:
  imports:
    - mne_bids_pipeline
  commands:
    - pip check
    - mne_bids_pipeline --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/mne-bids-pipeline/
  summary: A full-flegded processing pipeline for your MEG and EEG data
  license: BSD-3-Clause AND Apache-2.0
  license_file:
    - LICENSE.txt
    - mne_bids_pipeline/steps/freesurfer/contrib/LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - hoechenberger
