{% set name = "mne-bids-pipeline" %}
{% set version = "1.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 35a10ae04b6bdeb64713eb643a4b2b6a6edceb4ebd9d4358b8b8288150c33ee5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - mne_bids_pipeline = mne_bids_pipeline._main:main

requirements:
  host:
    - pip
    - setuptools >=65.0
    - setuptools_scm
    - python >=3.9
  run:
    - python >=3.9
    - psutil
    - packaging
    - joblib >=0.14
    - threadpoolctl
    - dask
    - bokeh <3
    - jupyter-server-proxy
    - scikit-learn
    - numpy
    - scipy
    - matplotlib-base
    - pandas
    - seaborn
    - json_tricks
    - rich
    - python-picard
    - qtpy
    - pyvista
    - pyvistaqt
    - openpyxl
    - autoreject
    - mne-base >=1.2
    - h5io
    - mne-bids >=0.11.1
    - nibabel
    - filelock
    - pydantic
    - setuptools >=65.0  # https://github.com/pypa/setuptools_scm/#retrieving-package-version-at-runtime

test:
  imports:
    - mne_bids_pipeline
  commands:
    - pip check
    - mne_bids_pipeline --version
  requires:
    - pip

about:
  home: https://pypi.org/project/mne-bids-pipeline/
  summary: A standardized processing pipeline for your MEG and EEG data
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - larsoner
    - hoechenberger
